#!/usr/bin/env bash
# Guards writes in cw projects.
# Allowed: files inside existing repo subdirs, .env.<repo>.{global,override} at project root.
# Blocked: everything else at project root, .env at repo root (autogenerated).

INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

[ -z "$FILE" ] && exit 0

# Use the stable project root from cw, not the potentially-changed cwd
PROJECT_ROOT="${CW_PROJECT_DIR:-}"
[ -z "$PROJECT_ROOT" ] && exit 0

# If file is not under the project root at all, allow it
case "$FILE" in
  "$PROJECT_ROOT"/*) ;;
  *) exit 0 ;;
esac

# Get path relative to project root
REL="${FILE#$PROJECT_ROOT/}"

# Allow: files inside existing repo subdirs (except repo-root .env), project-root .env
# Block: everything else
ALLOWED=false
case "$REL" in
  "") ALLOWED=true ;;
  .cw/*) ALLOWED=true ;;
  */*)
    DIR="${REL%%/*}"
    REST="${REL#*/}"
    if [ -d "$PROJECT_ROOT/$DIR" ]; then
      # Block .env at repo root — it's autogenerated by cw
      if [ "$REST" = ".env" ]; then
        echo "You're not allowed to write $DIR/.env — it's autogenerated by cw. Edit .env.$DIR.global or .env.$DIR.override in the project root instead." >&2
        exit 2
      fi
      ALLOWED=true
    fi
    ;;
  .env.*.global|.env.*.override) ALLOWED=true ;;
esac

if [ "$ALLOWED" = false ]; then
  REPOS=$(find "$PROJECT_ROOT" -maxdepth 1 -mindepth 1 -type d ! -name '.*' -printf '%f\n' | sort | tr '\n' ',' | sed 's/,$//')
  echo "You're not allowed to write in the project root. Write inside a repo instead: ${REPOS:-none}" >&2
  exit 2
fi
